// Sample orders for testing the dashboard UI before Supabase is wired up.
// Shape matches the real `orders` table exactly (see supabase/schema.sql).
import type { Order } from "./types";

export const mockOrders: Order[] = [
  {
    id: "ord_1",
    client_id: null,
    category: "b2c",
    source: "manual",
    customer_name: "Олена Марчетті",
    customer_contact: "@olena.m",
    item_summary_uk: "Весільний торт, 3 яруси, ваніль",
    item_summary_en: "3-tier vanilla wedding cake",
    item_details_uk: { notes: "На 60 осіб, без горіхів, золоте листя" },
    item_details_en: { notes: "Serves 60, nut-free, gold leaf finish" },
    status: "new",
    deposit_status: "paid",
    total_amount: 480,
    due_date: "2026-09-06",
    raw_message: null,
    created_at: "2026-08-20T10:00:00Z",
    updated_at: "2026-08-20T10:00:00Z",
  },
  {
    id: "ord_2",
    client_id: "client_1",
    category: "b2b",
    source: "telegram",
    customer_name: "Corner Cafe Kyiv",
    customer_contact: "@cornercafe_kyiv",
    item_summary_uk: "Круасани, 200 шт на тиждень",
    item_summary_en: "Weekly croissant supply — 200 units",
    item_details_uk: { notes: "Постійне замовлення, вт/пт доставка" },
    item_details_en: { notes: "Standing order, Tues/Fri delivery" },
    status: "confirmed",
    deposit_status: "n/a",
    total_amount: 340,
    due_date: "2026-09-02",
    raw_message: null,
    created_at: "2026-08-19T10:00:00Z",
    updated_at: "2026-08-19T10:00:00Z",
  },
  {
    id: "ord_3",
    client_id: null,
    category: "b2c",
    source: "manual",
    customer_name: "Софія Бондар",
    customer_contact: "+380501234567",
    item_summary_uk: "Дитячий торт на замовлення",
    item_summary_en: "Custom birthday cake",
    item_details_uk: { notes: "Тема динозаврів, на 12 осіб — прийнято по телефону" },
    item_details_en: { notes: "Dinosaur theme, serves 12 — taken by phone" },
    status: "new",
    deposit_status: "pending",
    total_amount: 95,
    due_date: "2026-09-03",
    raw_message: null,
    created_at: "2026-08-18T10:00:00Z",
    updated_at: "2026-08-18T10:00:00Z",
  },
  {
    id: "ord_4",
    client_id: null,
    category: "b2c",
    source: "manual",
    customer_name: "Марта Коваленко",
    customer_contact: "@marta.k",
    item_summary_uk: "Вежа з макаронс",
    item_summary_en: "Macaron tower",
    item_details_uk: { notes: "150 штук, 5 смаків, заручини" },
    item_details_en: { notes: "150 pieces, 5 flavors, engagement party" },
    status: "in_progress",
    deposit_status: "paid",
    total_amount: 260,
    due_date: "2026-09-01",
    raw_message: null,
    created_at: "2026-08-17T10:00:00Z",
    updated_at: "2026-08-17T10:00:00Z",
  },
  {
    id: "ord_5",
    client_id: "client_2",
    category: "b2b",
    source: "website_form",
    customer_name: "Lviv Hotel Group",
    customer_contact: "procurement@lvivhotel.ua",
    item_summary_uk: "Випічка на сніданок",
    item_summary_en: "Breakfast pastry order",
    item_details_uk: { notes: "80 шт асорті, щопонеділка" },
    item_details_en: { notes: "80 assorted, recurring Mondays" },
    status: "ready",
    deposit_status: "n/a",
    total_amount: 210,
    due_date: "2026-08-31",
    raw_message: null,
    created_at: "2026-08-16T10:00:00Z",
    updated_at: "2026-08-16T10:00:00Z",
  },
  {
    id: "ord_6",
    client_id: "client_3",
    category: "standard_line",
    source: "website_form",
    customer_name: "Fresh Mart Kyiv",
    customer_contact: "buyer@freshmart.ua",
    item_summary_uk: "Стандартизована лінійка — набір 12 SKU",
    item_summary_en: "Standardized line — 12 SKU box",
    item_details_uk: { notes: "Щотижневе замовлення, роздрібна упаковка" },
    item_details_en: { notes: "Weekly standing order, packaged retail line" },
    status: "completed",
    deposit_status: "n/a",
    total_amount: 610,
    due_date: "2026-08-30",
    raw_message: null,
    created_at: "2026-08-15T10:00:00Z",
    updated_at: "2026-08-15T10:00:00Z",
  },
  {
    id: "ord_7",
    client_id: "client_1",
    category: "b2b",
    source: "telegram",
    customer_name: "Corner Cafe Kyiv",
    customer_contact: "@cornercafe_kyiv",
    item_summary_uk: "Круасани, 250 шт — збільшене замовлення",
    item_summary_en: "Croissants, 250 units — increased order",
    item_details_uk: { notes: "Просять збільшити на 50 шт з наступного тижня" },
    item_details_en: { notes: "Asking to increase by 50 units starting next week" },
    status: "pending_review",
    deposit_status: "n/a",
    total_amount: null,
    due_date: null,
    raw_message: "Доброго дня! Можна з наступного тижня замовляти на 50 круасанів більше?",
    created_at: "2026-09-17T09:00:00Z",
    updated_at: "2026-09-17T09:00:00Z",
  },
];
