// Sample orders for testing the dashboard UI before Supabase is wired up.
// Shape matches the real `orders` table exactly (see supabase/schema.sql).
import type { Order } from "./types";

export const mockOrders: Order[] = [
  {
    id: "ord_1",
    client_id: null,
    source: "manual",
    customer_name: "Sunny Side Cafe",
    customer_contact: "@sunnyside_cafe",
    item_summary_uk: "Чізкейк Нью-Йорк ×2, Наполеон ×1",
    item_summary_en: "New York cheesecake ×2, Napoleon ×1",
    item_details_uk: { notes: "Перше замовлення, доставка в п'ятницю" },
    item_details_en: { notes: "First order, Friday delivery" },
    status: "new",
    deposit_status: "paid",
    total_amount: 480,
    due_date: "2026-09-06",
    raw_message: null,
    created_at: "2026-08-20T10:00:00Z",
    updated_at: "2026-08-20T10:00:00Z",
  },
  {
    id: "ord_2",
    client_id: "client_1",
    source: "telegram",
    customer_name: "Corner Cafe Kyiv",
    customer_contact: "@cornercafe_kyiv",
    item_summary_uk: "Круасани, 200 шт на тиждень",
    item_summary_en: "Weekly croissant supply — 200 units",
    item_details_uk: { notes: "Постійне замовлення, вт/пт доставка" },
    item_details_en: { notes: "Standing order, Tues/Fri delivery" },
    status: "confirmed",
    deposit_status: "n/a",
    total_amount: 340,
    due_date: "2026-09-02",
    raw_message: null,
    created_at: "2026-08-19T10:00:00Z",
    updated_at: "2026-08-19T10:00:00Z",
  },
  {
    id: "ord_3",
    client_id: null,
    source: "manual",
    customer_name: "Kyiv Book Cafe",
    customer_contact: "+380501234567",
    item_summary_uk: "Еклери асорті ×12, Макарони ×12",
    item_summary_en: "Assorted eclairs ×12, macarons ×12",
    item_details_uk: { notes: "Прийнято по телефону, доставка в середу" },
    item_details_en: { notes: "Taken by phone, Wednesday delivery" },
    status: "new",
    deposit_status: "pending",
    total_amount: 95,
    due_date: "2026-09-03",
    raw_message: null,
    created_at: "2026-08-18T10:00:00Z",
    updated_at: "2026-08-18T10:00:00Z",
  },
  {
    id: "ord_4",
    client_id: null,
    source: "manual",
    customer_name: "Lviv Hotel Group",
    customer_contact: "@lvivhotel",
    item_summary_uk: "Макарони 5 смаків ×150",
    item_summary_en: "Macarons, 5 flavours ×150",
    item_details_uk: { notes: "Для банкету, доставка в понеділок" },
    item_details_en: { notes: "For a banquet, Monday delivery" },
    status: "in_progress",
    deposit_status: "paid",
    total_amount: 260,
    due_date: "2026-09-01",
    raw_message: null,
    created_at: "2026-08-17T10:00:00Z",
    updated_at: "2026-08-17T10:00:00Z",
  },
  {
    id: "ord_5",
    client_id: "client_2",
    source: "website_form",
    customer_name: "Lviv Hotel Group",
    customer_contact: "procurement@lvivhotel.ua",
    item_summary_uk: "Випічка на сніданок",
    item_summary_en: "Breakfast pastry order",
    item_details_uk: { notes: "80 шт асорті, щопонеділка" },
    item_details_en: { notes: "80 assorted, recurring Mondays" },
    status: "ready",
    deposit_status: "n/a",
    total_amount: 210,
    due_date: "2026-08-31",
    raw_message: null,
    created_at: "2026-08-16T10:00:00Z",
    updated_at: "2026-08-16T10:00:00Z",
  },
  {
    id: "ord_6",
    client_id: "client_3",
    source: "website_form",
    customer_name: "Fresh Mart Kyiv",
    customer_contact: "buyer@freshmart.ua",
    item_summary_uk: "Круасани асорті ×60, Донати ×30",
    item_summary_en: "Assorted croissants ×60, donuts ×30",
    item_details_uk: { notes: "Щотижневе замовлення" },
    item_details_en: { notes: "Weekly standing order" },
    status: "completed",
    deposit_status: "n/a",
    total_amount: 610,
    due_date: "2026-08-30",
    raw_message: null,
    created_at: "2026-08-15T10:00:00Z",
    updated_at: "2026-08-15T10:00:00Z",
  },
  {
    id: "ord_7",
    client_id: "client_1",
    source: "telegram",
    customer_name: "Corner Cafe Kyiv",
    customer_contact: "@cornercafe_kyiv",
    item_summary_uk: "Круасани, 250 шт — збільшене замовлення",
    item_summary_en: "Croissants, 250 units — increased order",
    item_details_uk: { notes: "Просять збільшити на 50 шт з наступного тижня" },
    item_details_en: { notes: "Asking to increase by 50 units starting next week" },
    status: "pending_review",
    deposit_status: "n/a",
    total_amount: null,
    due_date: null,
    raw_message: "Доброго дня! Можна з наступного тижня замовляти на 50 круасанів більше?",
    created_at: "2026-09-17T09:00:00Z",
    updated_at: "2026-09-17T09:00:00Z",
  },
];
